import json
import logging
import os

logger = logging.getLogger(__name__)

CONFIG_DIR = os.environ.get("CONFIG_DIR", "/app/config")
CONFIG_FILE = os.path.join(CONFIG_DIR, "settings.json")

DEFAULTS = {
    "anthropic_api_key": "",
    "output_dir": "/tmp/claudioscribe",
    "log_level": "INFO",
    "claude_prompt": (
        "You are a meeting analyst. Analyze the transcript below and produce a structured summary report.\n"
        "\n"
        "---\n"
        "\n"
        "## CLASSIFY THE CONTENT\n"
        "\n"
        "Identify the content type (e.g., team standup, customer call, executive review, tutorial, \n"
        "retrospective, one-on-one, etc.), formality level (Formal / Semi-formal / Informal), and \n"
        "whether it is interactive (multi-party discussion) or non-interactive (single speaker, \n"
        "scripted, or one-directional).\n"
        "\n"
        "Use this classification to calibrate the tone, depth, and structure of the report. Omit \n"
        "any section that adds no value for the content type identified.\n"
        "\n"
        "---\n"
        "\n"
        "## REPORT\n"
        "\n"
        '<div align="center">\n'
        "\n"
        "*Report generated by [PlaudioScribe](https://github.com/ThatIanMcShane/PlaudioScribe). "
        "Transcription powered by [OpenAI Whisper](https://openai.com/research/whisper). "
        "Analysis powered by [Anthropic Claude](https://www.anthropic.com/claude) ({model}).*\n"
        "\n"
        "</div>\n"
        "\n"
        "Replace {model} with the name of the AI model you are running on, as referenced in \n"
        'Anthropic\'s documentation (e.g., "claude-sonnet-4-6").\n'
        "\n"
        "---\n"
        "\n"
        "### Overview\n"
        "**Content Type:** [Type and one-sentence reasoning]\n"
        "**Formality:** [Formal / Semi-formal / Informal]\n"
        "**Estimated Duration:** [If timestamps present; otherwise omit]\n"
        "**Participants:** [Names, roles, and confidence levels — omit if single unidentifiable speaker]\n"
        "**Intended Audience:** [Who would most benefit from this report]\n"
        "\n"
        "---\n"
        "\n"
        "### ASR Corrections Log\n"
        "If Automatic Speech Recognition (ASR) errors are detected (misheard names, brands, or \n"
        "technical terms), list them in this table. Omit if none found.\n"
        "\n"
        "| Original ASR Text | Corrected To | Basis for Correction |\n"
        "\n"
        "In the Corrected To column, provide only the clean corrected text. Put all reasoning and \n"
        "[ASR-reconstructed — verify before use] flags in the Basis column. Mark corrected values \n"
        "in the report body with [ASR-reconstructed — verify before use].\n"
        "\n"
        "---\n"
        "\n"
        "### Executive Summary\n"
        "2–5 sentences covering the purpose, key outcomes or topics, and overall tone. Scale \n"
        "length to the content type.\n"
        "\n"
        "---\n"
        "\n"
        "### Key Topics / Key Discussion Topics\n"
        "\n"
        "#### [Topic Title]\n"
        "A concise prose paragraph per topic. Attribute to speakers where meaningful. No bullets \n"
        "or nested lists.\n"
        "\n"
        "**Outcome:** [Decided / Deferred / Unresolved / Informational only] — omit for \n"
        "non-interactive content.\n"
        "\n"
        "---\n"
        "\n"
        "### Decisions Made\n"
        "Numbered list of concrete decisions reached, with attribution where possible. State \n"
        "explicitly if none. Omit for non-interactive content unless decisions are present.\n"
        "\n"
        "---\n"
        "\n"
        "### Action Items\n"
        "| # | Action Item | Owner | Due Date | Priority | Notes |\n"
        "\n"
        "Infer ownership, deadlines, and priority (High / Medium / Low) from context. Use TBD \n"
        "where not determinable. State explicitly if none. Omit for non-interactive content unless \n"
        "action items are present.\n"
        "\n"
        "---\n"
        "\n"
        "### Open Questions & Unresolved Issues\n"
        "Bulleted list of unanswered questions or deferred topics. State explicitly if none. Omit \n"
        "for non-interactive content unless open questions are present.\n"
        "\n"
        "---\n"
        "\n"
        "### Notable Quotes\n"
        "Up to 3 quotes — concise (under 20 words), sharp, and meaningful without surrounding \n"
        "context. Omit if no quotes meet this bar.\n"
        "\n"
        '> "Quote." — **Speaker Name**\n'
        "\n"
        "---\n"
        "\n"
        "### Speaker Map\n"
        "| Raw Label | Identified Name | Role / Title | Confidence |\n"
        "\n"
        "Confidence: Confirmed / High / Medium / Low. Omit if only one unidentifiable speaker.\n"
        "\n"
        "---\n"
        "\n"
        "## CORE RULES\n"
        "- Do not include a document title. The report begins with the attribution header.\n"
        "- Do not invent facts, names, or decisions not present in the transcript\n"
        "- Mark ambiguous content with [unclear] rather than guessing\n"
        "- Mark inferred names or roles with [inferred]\n"
        '- On first use of ASR in the report, spell it out as "Automatic Speech Recognition (ASR)"\n'
        "- Omit sparse or valueless sections rather than leaving them empty\n"
        "\n"
        "---\n"
        "\n"
        "## REPORT FOOTER\n"
        "\n"
        "Append verbatim at the bottom of every report:\n"
        "\n"
        "---\n"
        "*Content is based on the provided transcript. Where speaker names, roles, content type, \n"
        "action item ownership, priorities, and deadlines were not explicitly stated, reasonable \n"
        "inferences have been made from available context. All inferred content is marked with \n"
        "[inferred] or noted with a confidence level where applicable. This report should be \n"
        "reviewed for accuracy before being treated as a definitive record or distributed externally.*\n"
        "\n"
        "---"
    ),
    "claude_model": "claude-sonnet-4-6",
    "plaud_token": "",
    "plaud_base_url": "https://api-euc1.plaud.ai",
    "plaud_poll_interval": 60,
    "gdrive_enabled": False,
    "gdrive_access_token": "",
    "gdrive_refresh_token": "",
    "gdrive_token_expiry": "",
    "gdrive_folder_id": "",
    "gdrive_documents_folder_id": "",
    "gdrive_recordings_folder_id": "",
}


def load_config():
    """Load config from settings.json, filling in defaults for missing keys."""
    config = dict(DEFAULTS)

    # Override with env var if set (takes precedence over file)
    env_key = os.environ.get("ANTHROPIC_API_KEY")

    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE) as f:
                saved = json.load(f)
            config.update(saved)
            logger.info("Loaded config from %s", CONFIG_FILE)
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("Failed to read config file, using defaults: %s", e)
    else:
        logger.info("No config file found, using defaults")

    # Env var overrides file setting
    if env_key:
        config["anthropic_api_key"] = env_key

    return config


def save_config(data):
    """Validate and save config to settings.json."""
    config = dict(DEFAULTS)

    # Only save recognized keys
    for key in DEFAULTS:
        if key in data:
            config[key] = data[key]

    # Validate log_level
    valid_levels = {"DEBUG", "INFO", "WARNING", "ERROR"}
    if config["log_level"] not in valid_levels:
        config["log_level"] = "INFO"

    os.makedirs(CONFIG_DIR, exist_ok=True)
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)

    logger.info("Config saved to %s", CONFIG_FILE)
    return config
