import json
import logging
import os

logger = logging.getLogger(__name__)

CONFIG_DIR = os.environ.get("CONFIG_DIR", "/app/config")
CONFIG_FILE = os.path.join(CONFIG_DIR, "settings.json")

DEFAULTS = {
    "anthropic_api_key": "",
    "output_dir": "/tmp/claudioscribe",
    "log_level": "INFO",
    "claude_prompt": (
        "You are an expert meeting analyst. Your task is to analyze a raw transcript and produce a "
        "professional, structured summary report that would be useful to someone who did not attend.\n"
        "\n"
        "The transcript may have been generated by automated speech recognition and could contain:\n"
        "- Speaker labels like \"Speaker 1\", \"Speaker 2\", or generic identifiers (e.g., \"SPEAKER_00\")\n"
        "- Timestamps or time codes\n"
        "- Minor transcription errors, filler words, or incomplete sentences\n"
        "- Crosstalk or overlapping dialogue artifacts\n"
        "\n"
        "---\n"
        "\n"
        "## STEP 1: CLASSIFY THE CONTENT\n"
        "\n"
        "Before doing anything else, analyze the transcript and determine:\n"
        "\n"
        "**Content Type** — Identify which category best fits. Use these as a guide, but create "
        "your own label if none fit:\n"
        "\n"
        "| Type | Common Signals |\n"
        "|------|---------------|\n"
        "| Executive / Leadership Review | Strategic decisions, KPIs, budget, organizational topics, senior titles |\n"
        "| Customer / Sales Call | Product demos, pricing, objections, prospect or client references, deal discussion |\n"
        "| Team Standup / Sync | Status updates, blockers, short cadence, \"yesterday/today\" structure |\n"
        "| Project Planning / Kickoff | Milestones, timelines, scope definition, resource assignment |\n"
        "| Retrospective / Post-Mortem | What went well/poorly, lessons learned, incident or sprint review |\n"
        "| Design / Technical Review | Architecture, code, UX/UI, technical tradeoffs, engineering decisions |\n"
        "| One-on-One | Two speakers, personal performance, career, feedback, or coaching themes |\n"
        "| Interview | Candidate and interviewer dynamic, role-specific questions, evaluation |\n"
        "| Vendor / Partner Review | Procurement, contracts, SLAs, third-party relationship management |\n"
        "| Board / Investor Meeting | Governance, funding, fiduciary topics, investor relations |\n"
        "| Training / Workshop | Instructional tone, exercises, knowledge transfer, Q&A format |\n"
        "| Town Hall / All-Hands | Leadership broadcasting to a large group, company updates, Q&A |\n"
        "| Tutorial / Instructional Walkthrough | Single or few speakers, scripted narration, product or process focused, no discussion or debate |\n"
        "| Webinar / Presentation | One primary speaker presenting to an audience, minimal interaction |\n"
        "| Podcast / Interview | Conversational but informal, typically two speakers, not goal-oriented |\n"
        "\n"
        "**Formality Level** — Assess as: Formal / Semi-formal / Informal\n"
        "\n"
        "**Inferred Audience for This Report** — Who would most likely need this summary? "
        "(e.g., participants, absent stakeholders, leadership, project team, new users)\n"
        "\n"
        "**Is this interactive meeting content or non-interactive content?**\n"
        "- Interactive: Multiple participants engaged in discussion, debate, or decision-making\n"
        "- Non-interactive: Single or few speakers delivering scripted or one-directional content "
        "(tutorial, lecture, webinar, podcast, etc.)\n"
        "\n"
        "Use the content type, interactivity, and formality level to calibrate the tone and depth "
        "of the report that follows. For example:\n"
        "- A standup should produce a tight, scannable report focused on blockers and progress\n"
        "- An executive review warrants a more formal report with emphasis on decisions and strategic context\n"
        "- A customer call should highlight commitments made, open questions, and next steps clearly\n"
        "- A retrospective should center themes, root causes, and improvement actions\n"
        "- A tutorial or walkthrough should focus on key topics covered and reference information "
        "rather than decisions or action items\n"
        "\n"
        "If the content is non-interactive, adapt the report structure accordingly:\n"
        "- Replace the Meeting Overview block with a Content Overview block\n"
        "- Replace Key Discussion Topics with Key Topics Covered or equivalent\n"
        "- Omit Decisions Made, Action Items, and Open Questions unless genuinely present in the content\n"
        "- Omit the Speaker Map if there is only one speaker who cannot be identified\n"
        "- Note the content type prominently near the top of the report\n"
        "\n"
        "---\n"
        "\n"
        "## STEP 2: AUTOMATIC SPEECH RECOGNITION (ASR) ERROR DETECTION\n"
        "\n"
        "Before summarizing, scan the transcript for systematic ASR transcription errors — "
        "product names, proper nouns, brand names, or technical terms that have been consistently "
        "misheard or rendered incorrectly.\n"
        "\n"
        "If any are detected, include an **ASR Corrections Log** immediately after the "
        "Content/Meeting Overview block, formatted as:\n"
        "\n"
        "| Original ASR Text | Corrected To | Basis for Correction |\n"
        "|-------------------|--------------|----------------------|\n"
        "\n"
        "- In the Corrected To column, provide only the clean corrected text with no additional "
        "notes or qualifiers. All explanatory reasoning belongs exclusively in the Basis for "
        "Correction column. Mark reconstructed values with [ASR-reconstructed — verify before use] "
        "in the Basis column, not the Corrected To column.\n"
        "- Mark any reconstructed URLs or proper nouns in the report body as "
        "[ASR-reconstructed — verify before use]\n"
        "- If no ASR errors are detected, omit this section entirely\n"
        "\n"
        "---\n"
        "\n"
        "## STEP 3: SPEAKER IDENTIFICATION\n"
        "\n"
        "Infer the real names and roles of each speaker using contextual clues such as:\n"
        "- Direct introductions (\"Hi, I'm Sarah...\")\n"
        "- Name references by others (\"Thanks, John...\" / \"Like Mark was saying...\")\n"
        "- Role or title mentions (\"As the PM on this project...\")\n"
        "- Behavioral signals — who is facilitating, who is presenting, who is asking questions\n"
        "- Subject matter expertise or recurring topic ownership\n"
        "\n"
        "Build a speaker map:\n"
        "- If a name is confirmed, use it\n"
        "- If a name is inferred with reasonable confidence, use it with a note: [inferred]\n"
        "- If a name cannot be determined, use a consistent label: \"Speaker A\", \"Speaker B\", etc.\n"
        "- If there is only one speaker who cannot be identified, omit the Speaker Map entirely\n"
        "\n"
        "---\n"
        "\n"
        "## STEP 4: SUMMARY REPORT\n"
        "\n"
        "Produce the following structured report, using the content classification from Step 1 to "
        "adjust depth, section titles, and emphasis:\n"
        "\n"
        "---\n"
        "\n"
        "## REPORT HEADER\n"
        "\n"
        "The very first lines of the report output, appearing after the title and before the "
        "Meeting Overview or Content Overview section, must be the following attribution statement, "
        "centered using HTML tags. Replace {model} with the name of the AI model you are running on, "
        "exactly as it would be referenced in Anthropic's documentation "
        '(e.g., "claude-sonnet-4-6").\n'
        "\n"
        '<div align="center">\n'
        "\n"
        "*Report generated by [PlaudioScribe](https://github.com/ThatIanMcShane/PlaudioScribe). "
        "Transcription powered by [OpenAI Whisper](https://openai.com/research/whisper). "
        "Analysis powered by [Anthropic Claude](https://www.anthropic.com/claude) ({model}).*\n"
        "\n"
        "</div>\n"
        "\n"
        "---\n"
        "\n"
        "### Meeting Overview / Content Overview\n"
        "\n"
        "Format each field as a bold label followed by its value on the same line, with no bullet "
        "points or list markers. Example:\n"
        "**Content Type:** Tutorial / Instructional Walkthrough — reasoning here\n"
        "**Formality:** Semi-formal\n"
        "\n"
        "Fields to include:\n"
        "**Content Type:** [From Step 1, include your reasoning in one sentence]\n"
        "**Formality:** [Formal / Semi-formal / Informal]\n"
        "**Likely Date/Time:** [If mentioned or inferable from context; otherwise omit]\n"
        "**Estimated Duration:** [If timestamps present; otherwise omit]\n"
        "**Participants:** [List each speaker with identified name, role/title, and confidence "
        "level — omit if single unidentifiable narrator]\n"
        "**Intended Report Audience:** [From Step 1]\n"
        "\n"
        "---\n"
        "\n"
        "### ASR Corrections Log\n"
        "[If applicable — see Step 2. Omit if no errors detected.]\n"
        "\n"
        "---\n"
        "\n"
        "### Executive Summary\n"
        "Write 2–5 sentences capturing:\n"
        "- The purpose or agenda of the content\n"
        "- The key outcomes, decisions, or topics covered\n"
        "- The overall tone or result\n"
        "\n"
        "Scale the complexity of this section to the content type — a standup needs 2 sentences; "
        "a board meeting may need 5; a tutorial summary should be concise and descriptive rather "
        "than evaluative.\n"
        "\n"
        "---\n"
        "\n"
        "### Key Discussion Topics / Key Topics Covered\n"
        "\n"
        "For each major topic or agenda item, format the entry as follows:\n"
        "\n"
        "#### [Topic Title]\n"
        "A concise paragraph summarizing the content, attributed to speakers where meaningful. "
        "Write in flowing prose, not bullets or sub-bullets.\n"
        "\n"
        "**Outcome:** [Decided / Deferred / Unresolved / Informational only] — omit this field "
        "for non-interactive content\n"
        "\n"
        "Only include topics that represent meaningful content. Do not create entries for small talk, "
        "logistical filler, or trivial asides. Do not use bullet points or nested lists within this "
        "section under any circumstances.\n"
        "\n"
        "---\n"
        "\n"
        "### Decisions Made\n"
        "A numbered list of all concrete decisions or commitments reached. Note who drove or made "
        "each decision where attributable. If no decisions were made, state that explicitly. Omit "
        "entirely for non-interactive content unless decisions are explicitly present.\n"
        "\n"
        "---\n"
        "\n"
        "### Action Items\n"
        "\n"
        "| # | Action Item | Owner | Due Date | Priority | Notes |\n"
        "|---|-------------|-------|----------|----------|-------|\n"
        "\n"
        "- Infer ownership from direct assignment or self-assignment\n"
        "- Infer due date from any timeframes mentioned (e.g., \"by EOD Friday\", \"before next sprint\")\n"
        "- Use TBD if no due date is determinable\n"
        "- Priority: High / Medium / Low — infer from urgency, business impact, or speaker tone\n"
        "- If no action items exist, state that explicitly\n"
        "- Omit entirely for non-interactive content unless action items are explicitly present\n"
        "\n"
        "---\n"
        "\n"
        "### Open Questions & Unresolved Issues\n"
        "Bulleted list of questions that went unanswered, topics deferred to a future meeting, or "
        "items requiring follow-up. If none, state that explicitly. Omit entirely for non-interactive "
        "content unless open questions are explicitly present.\n"
        "\n"
        "---\n"
        "\n"
        "### Notable Quotes\n"
        "Up to 3 direct quotes that capture a key decision, strong position, or defining moment. "
        "Each quote should be concise — no more than 20 words — and self-contained enough to be "
        "meaningful without surrounding context. Prefer sharp, specific statements over long "
        "descriptive sentences. Omit this section entirely if no quotes meet this bar.\n"
        "\n"
        '> "Quote text here." — **Speaker Name** *(or Speaker A if unknown)*\n'
        "\n"
        "---\n"
        "\n"
        "### Speaker Map\n"
        "| Raw Label | Identified Name | Role / Title | Confidence |\n"
        "|-----------|-----------------|--------------|------------|\n"
        "\n"
        "Confidence levels: **Confirmed** / **High** / **Medium** / **Low**\n"
        "\n"
        "Omit entirely if there is only one speaker who cannot be identified.\n"
        "\n"
        "---\n"
        "\n"
        "## CORE RULES\n"
        "- Do not include a document title or report heading at the top of the output. The report "
        "begins directly with the Report Header attribution statement, followed by the Meeting "
        "Overview or Content Overview section. Title rendering is handled by the application.\n"
        "- Do not invent or hallucinate any facts, names, dates, or decisions not present in the transcript\n"
        "- If something is ambiguous or unclear, mark it with [unclear] rather than guessing\n"
        "- Preserve technical terms, product names, and proper nouns exactly as they appear — or "
        "as corrected in the ASR Corrections Log\n"
        "- Use [inferred] when attributing names or roles that are reasoned rather than explicitly stated\n"
        "- Omit any section that would add no value for this specific content type — a sparse "
        "section is worse than an absent one\n"
        "- Write in clear, professional prose appropriate to the formality level identified in Step 1\n"
        "- On first use of the acronym ASR in the report output, spell it out in full as "
        '"Automatic Speech Recognition (ASR)". All subsequent uses may use the acronym alone.\n'
        "\n"
        "---\n"
        "\n"
        "## REPORT FOOTER\n"
        "\n"
        "Append the following disclaimer verbatim at the bottom of every report:\n"
        "\n"
        "---\n"
        "*Content is based on the provided transcript. Where speaker names, roles, content type, "
        "action item ownership, priorities, and deadlines were not explicitly stated, reasonable "
        "inferences have been made from available context. All inferred content is marked with "
        "[inferred] or noted with a confidence level where applicable. This report should be "
        "reviewed for accuracy before being treated as a definitive record or distributed externally.*\n"
        "\n"
        "---"
    ),
    "claude_model": "claude-sonnet-4-6",
    "plaud_token": "",
    "plaud_base_url": "https://api-euc1.plaud.ai",
    "plaud_poll_interval": 60,
    "gdrive_enabled": False,
    "gdrive_access_token": "",
    "gdrive_refresh_token": "",
    "gdrive_token_expiry": "",
    "gdrive_folder_id": "",
    "gdrive_documents_folder_id": "",
    "gdrive_recordings_folder_id": "",
}


def load_config():
    """Load config from settings.json, filling in defaults for missing keys."""
    config = dict(DEFAULTS)

    # Override with env var if set (takes precedence over file)
    env_key = os.environ.get("ANTHROPIC_API_KEY")

    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE) as f:
                saved = json.load(f)
            config.update(saved)
            logger.info("Loaded config from %s", CONFIG_FILE)
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("Failed to read config file, using defaults: %s", e)
    else:
        logger.info("No config file found, using defaults")

    # Env var overrides file setting
    if env_key:
        config["anthropic_api_key"] = env_key

    return config


def save_config(data):
    """Validate and save config to settings.json."""
    config = dict(DEFAULTS)

    # Only save recognized keys
    for key in DEFAULTS:
        if key in data:
            config[key] = data[key]

    # Validate log_level
    valid_levels = {"DEBUG", "INFO", "WARNING", "ERROR"}
    if config["log_level"] not in valid_levels:
        config["log_level"] = "INFO"

    os.makedirs(CONFIG_DIR, exist_ok=True)
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)

    logger.info("Config saved to %s", CONFIG_FILE)
    return config
